project_id = "ogzdqhvpsobpwxteqpnx"

[functions.verify-email]
verify_jwt = false

[functions.send-campaign-email]
verify_jwt = true

[functions.track-email-open]
verify_jwt = false

[functions.handle-email-reply]
verify_jwt = false

[functions.process-scheduled-emails]
verify_jwt = false