// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { authStorage } from '@/utils/authStorage';

const SUPABASE_URL = "https://ogzdqhvpsobpwxteqpnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nemRxaHZwc29icHd4dGVxcG54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTYyMjgsImV4cCI6MjA3MzY5MjIyOH0.jRYL7948dYqxPu0V5NyW3v-3J_wlUPrvktGK3SU9yV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});